name: Sync Public Folder to Public Repo

on:
  push:
    branches: [ main ]
  workflow_dispatch:  # allows manual triggering

permissions: 
  contents: write

jobs:
  sync-public:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout full repo
        uses: actions/checkout@v4
        with:
          fetch-depth: 0  # full history needed for subtree

      - name: Configure Git
        run: |
          git config user.name "DexterCarpenter"
          git config user.email "dexter.carpenter03@gmail.com"
#          git config user.name "GitHub Action"
#          git config user.email "actions@github.com"
        
      - name: Split the PublicPublish folder
        run: |
          git subtree split --prefix=PublicPublish -b public-split

      - name: Push to public repo using PAT
        env:
          GH_TOKEN: ${{ secrets.GH_PUBLIC_PAT }}
        run: |
          git remote add public https://x-access-token:${{ secrets.GH_PUBLIC_PAT }}@github.com/DexterCarpenter/ObsidianGitVault.Public.git
          git push public public-split:main --force

    #   - name: Push to destination repository
    #     run: |
    #       git config --global user.email "${{ secrets.USER_EMAIL }}"
    #       git config --global user.name "DexterCarpenter"
    #       git clone https://${{ env.ORG_NAME }}:${{ secrets.GH_PUBLIC_PAT }}@github.com/${{ env.ORG_NAME }}/destination-repo.git
    #       cd destination-repo
    #       git remote add ${{ env.ORIGINAL_REPO_NAME }} https://${{ env.ORG_NAME }}:${{ secrets.PAT }}@github.com/${{ env.ORG_NAME }}/${{ env.ORIGINAL_REPO_NAME }}.git
    #       git remote update
    #       git merge ${{ env.ORIGINAL_REPO_NAME }}/main
    #       git push origin main
    #   - name: Split the PublicPublish folder
    #     run: |
    #       git subtree split --prefix=PublicPublish -b public-split